---
title: "Cornwall 2011 RR and SMR Maps"
author: "E Farinre"
date: "22/08/2021"
output: html_document
---

```{r setup, include=FALSE}
# Packages
library(flexdashboard)
library(leaflet.providers)
library(plyr)
library(tidyverse)
library(spdep)
library(SpatialEpi)
library(rgdal)
library(tmap)
library(RSQLite)
library(tmaptools)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(broom)
library(plotly) 
library(geojsonio) 
library(mapview) 
library(crosstalk)
library(viridis)
library(reshape2)
library(shinyjs)
library(janitor)
library(car)
library(corrplot)
library(shades)
library(ggpubr)
library(RDS)
library(hrbrthemes)
library(rgeos)

# read in the postcode -> OA -> LSOA -> MSOA -> LA lookup table. filter for cornwall
cornwall1 <-  read_csv(("C:/Users/Emmanuel/OneDrive/Dissertation/data/PCD_OA_LSOA_MSOA_LAD_NOV20_UK_LU/PCD_OA_LSOA_MSOA_LAD_NOV20_UK_LU.csv"),
                      col_names = TRUE,
                      locale = locale(encoding = "Latin1")) %>%
  dplyr::filter(str_detect(ladnm, "Cornwall"))

# keep the code and name columns only
cornwall1 <- cornwall1[c("lsoa11cd", "lsoa11nm")]
# remove the duplicate lsoa rows, given that there is a row for each postcode
cornwall1 <- cornwall1[!duplicated(cornwall1[,c("lsoa11cd", "lsoa11nm")]),]

# Reading in the map of emgland with the lsoa boundaries
england_lsoas <- st_read("C:/Users/Emmanuel/OneDrive/Dissertation/data/Lower_Layer_Super_Output_Areas__December_2011__Boundaries_Full_Extent__BFE__EW_V3-shp/Lower_Layer_Super_Output_Areas__December_2011__Boundaries_Full_Extent__BFE__EW_V3.shp")

#filter to just cornwall
cornwall_lsoas <- inner_join(england_lsoas, cornwall1, by = c("LSOA11CD" = "lsoa11cd"))
cornwall_lsoas <- cornwall_lsoas[c("LSOA11CD", "LSOA11NM")]
rm(england_lsoas)


### time to start reading in the covariates for cornwall. Unlike London, Cornwall does not have a data store
# so some of the covariates wil have to be calculated here
# let's start by erading in the social renting % column which is already calculated
social_renting <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/cornwall_socialrenting.csv")
names(social_renting) <- c("names", "codes", "socialrenting_pc")

# now for the economic activity. you'll need to calculate the unemployment rate (economically active people who are unemployed)
# by divided the two columns and rounding to 1 decimal place to match the London rates
unemployment <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/cornwall_economicactivity.csv")
names(unemployment) <- c("names", "code", "active", "unemployed")
unemployment$unemployed_pc <- round(unemployment$unemployed/unemployment$active, digits = 1)
unemployment <- unemployment[c("code", "unemployed_pc")]

# merge the two together
covariates1 <- inner_join(unemployment, social_renting, by = c("code" = "codes"))
# reordering the columns
covariates1 <- covariates1[c("code", "names", "unemployed_pc", "socialrenting_pc")]

# now read in the persons per hectare data
popden <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/england_popdensity.csv")
names(popden) <- c("names", "code", "pop_density")
popden <- popden[c("code", "pop_density")]

covariates1 <- inner_join(covariates1, popden, by = c("code" = "code"))

# now read in the ethnicity grouping data
ethnicity <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/cornwall_ethnicity.csv")
names(ethnicity) <- c("names", "codes", "white_pc", "mixed_pc", "asian_pc", "black_pc", "other_pc")
ethnicity$bame_pc <- round(ethnicity$mixed_pc + ethnicity$asian_pc + ethnicity$black_pc + 
                             ethnicity$other_pc, digits = 1)
#drop the names column
ethnicity <- ethnicity[c("codes", "white_pc", "mixed_pc", "asian_pc", "black_pc", "other_pc", "bame_pc")]

# merge with covariates1
covariates1 <- inner_join(covariates1, ethnicity, by = c("code" = "codes"))


#################### now read in the CDRC Access to Health Assets and Hazards dataset # raw scores
covariates2 <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/allvariableslsoawdeciles.csv")
# filter for the lsoa code,  gp, a&e, pharmacy, green (passive) and green (active) accessbitlity columns
covariates2 <- covariates2[c("lsoa11", "gpp_dist", "ed_dist", "pharm_dist", "green_pas", "green_act")]
names(covariates2) <- c("lsoa", "gp_access", "ae_access", "pharm_access", "green_access_prop", "green_access_dist")


#################### read in the composite INDEX values CDRC Access to Health Assets and Hazards dataset 
covariates3 <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/ahahv2domainsindex.csv")
# filter for the lsoa code, health domain deciles and blue/green space domain deciles columns
covariates3 <- covariates3[c("lsoa11", "h_exp", "g_exp", "h_dec", "g_dec")]
names(covariates3) <- c("lsoa","health_access_valexp", "greenblue_access_valexp", "health_access_deciles", "greenblue_access_deciles")


# merge the dataframes together
cornwall_covariates <- inner_join(covariates1, covariates2, by = c("code" = "lsoa"))
# add the remaining columns via another merge
cornwall_covariates <- inner_join(cornwall_covariates, covariates3, by = c("code" = "lsoa"))

cornwall_covariates <- cornwall_covariates[c("code", "names", "pop_density", "green_access_prop", "green_access_dist", "unemployed_pc", "socialrenting_pc", "bame_pc")]

############ rename
names(cornwall_covariates) <- c("codes", "names", "pop_density","green_area", "distance_to_green",
                           "unemployment", "social_renters", "bame")


# join Cornwall data with the map of Cornwall 
map1 <- inner_join(cornwall_lsoas, cornwall_covariates, by = c("LSOA11CD" = "codes"))
# drop the repeated lsoa names column
drop <-  c("names")
map1 <- map1[,!(names(map1) %in% drop)]

# For the interactive map, because I'm using leaflet, I Need '+proj=longlat +datum=WGS84' 
# Checking projection of my map of Cornwall
#print(map1) #Returns Projected CRS: OSGB 1936 / British National Grid
# which has the epsg code of 4326
# Reproject
map1REPROJECTED <- map1 %>%
  st_transform(., 4326)


################################## READ IN THE RESULTS OF THE SAVED MODEL ABOVE ###############
load("cornwall.rds")

# Add these data points to the map of london, assigning the mean to the estimate of the relative risk
# and 0.025quant and 0.975quant to the lower and upper limits of 95% credible intervals of the risks
map1REPROJECTED$RR <-  cornwall$summary.fitted.values[, "mean"]
map1REPROJECTED$LL <-  cornwall$summary.fitted.values[, "0.025quant"]
map1REPROJECTED$UL <-  cornwall$summary.fitted.values[, "0.975quant"]


# read in the 2011 smr, exported from the data safe haven
smr_2011 <- read_csv("C:/Users/Emmanuel/OneDrive/Dissertation/data/smr_2011.csv")
# filter to just cornwall smrs
cornwall_smr <- inner_join(smr_2011, cornwall1, by = c("codes" = "lsoa11cd"))
cornwall_smr <- cornwall_smr[c("codes", "smr")]


# add smr column to mapReprojected
map1REPROJECTED$SMR <- cornwall_smr$smr
head(map1REPROJECTED)

############# Read in the London RR map then use it as the palette for the Cornwall RR mapping
# to keep the maps on the same sale
mapREPROJECTED <- st_read("C:/Users/Emmanuel/OneDrive/Dissertation/mapREPROJECTED_RR_ldn.shp")


rm(cornwall)
rm(cornwall_covariates)
rm(cornwall_lsoas)
rm(cornwall_smr)
rm(cornwall1)
rm(covariates1)
rm(covariates2)
rm(covariates3)
rm(ethnicity)
rm(map1)
rm(popden)
rm(smr_2011)
rm(social_renting)
rm(unemployment)



```




### Figure 2: Snapshot of the interactive map created using leaflet showing the neuropsychiatric hospitalisation SMRs in Cornwall LSOAs in 2011.
```{r}
################ ploting interactive map of the SMR
pal <- colorNumeric(palette = "YlOrRd", domain = mapREPROJECTED$SMR)
labels <- sprintf("<strong> %s </strong> <br/> SMR: %s",
                  map1REPROJECTED$LSOA11NM, round(map1REPROJECTED$SMR, 2)) %>%
  lapply(htmltools::HTML)

twenty_11 <- leaflet(map1REPROJECTED) %>% addTiles() %>%
  addPolygons(color = "grey", weight = 1, fillColor = ~pal(SMR), fillOpacity = 0.5,
              highlightOptions = highlightOptions(weight = 4), label = labels,
              labelOptions = labelOptions(style = list("font-weight" = "normal",
                                                       padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto")) %>%
  addLegend(pal = pal, values = ~SMR, opacity = 0.5, title = "SMR",
            position = "bottomright")

twenty_11

```





### Figure 12: Snapshot of the interactive map created using leaflet showing the neuropsychiatric hospitalisation RRs in Cornwall LSOAs in 2011.

```{r}
############### PLOTTING a Interactive map of the RR

# specify the palette
pal <- colorNumeric(palette = "YlOrRd", domain = mapREPROJECTED$SMR)
# specify the labels
labels <- sprintf("<strong> %s </strong> <br/> SMR: %s <br/> Person per hectare: %s <br/> Green area (km2): %s <br/> 
                  Distance to Greenery (km): %s <br/> RR: %s (%s, %s)",
                  map1REPROJECTED$LSOA11NM, round(map1REPROJECTED$SMR, 2),
                  map1REPROJECTED$pop_density,
                  round(map1REPROJECTED$green_area, 2),
                  round(map1REPROJECTED$distance_to_green, 2),
                  round(map1REPROJECTED$RR, 2), 
                  round(map1REPROJECTED$LL, 2), round(map1REPROJECTED$UL, 2) ) %>%
  lapply(htmltools::HTML)

# apply final touches and now plot
rr_twenty11 <- leaflet(map1REPROJECTED) %>% addTiles() %>%
  addPolygons(color = "grey", weight = 1, fillColor = ~pal(RR), fillOpacity = 0.5,
              highlightOptions = highlightOptions(weight = 4), label = labels,
              labelOptions = labelOptions(style = list("font-weight" = "normal",
                                                       padding = "3px 8px"),
                                          textsize = "15px",
                                          direction = "auto")) %>%
  addLegend(pal = pal, values = ~RR, opacity = 0.5, title = "RR",
            position = "bottomright")

rr_twenty11

```





